/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddBookMark: typeof import('./../components/HomeView/AddBookMark.vue')['default']
    BookMarkForm: typeof import('./../components/HomeView/BookMarkForm.vue')['default']
    BookMarkList: typeof import('./../components/HomeView/BookMarkList.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTree: typeof import('element-plus/es')['ElTree']
    ElTreeSelect: typeof import('element-plus/es')['ElTreeSelect']
    IconCommunity: typeof import('./../components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./../components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./../components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./../components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./../components/icons/IconTooling.vue')['default']
    Lock: typeof import('./../components/Lock.vue')['default']
    MyDialog: typeof import('./../components/MyDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./../components/HomeView/Settings.vue')['default']
    TheWelcome: typeof import('./../components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./../components/WelcomeItem.vue')['default']
  }
}

// For TSX support
declare global {
  const AddBookMark: typeof import('./../components/HomeView/AddBookMark.vue')['default']
  const BookMarkForm: typeof import('./../components/HomeView/BookMarkForm.vue')['default']
  const BookMarkList: typeof import('./../components/HomeView/BookMarkList.vue')['default']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
  const ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
  const ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
  const ElDialog: typeof import('element-plus/es')['ElDialog']
  const ElForm: typeof import('element-plus/es')['ElForm']
  const ElFormItem: typeof import('element-plus/es')['ElFormItem']
  const ElIcon: typeof import('element-plus/es')['ElIcon']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElTabPane: typeof import('element-plus/es')['ElTabPane']
  const ElTabs: typeof import('element-plus/es')['ElTabs']
  const ElTree: typeof import('element-plus/es')['ElTree']
  const ElTreeSelect: typeof import('element-plus/es')['ElTreeSelect']
  const IconCommunity: typeof import('./../components/icons/IconCommunity.vue')['default']
  const IconDocumentation: typeof import('./../components/icons/IconDocumentation.vue')['default']
  const IconEcosystem: typeof import('./../components/icons/IconEcosystem.vue')['default']
  const IconSupport: typeof import('./../components/icons/IconSupport.vue')['default']
  const IconTooling: typeof import('./../components/icons/IconTooling.vue')['default']
  const Lock: typeof import('./../components/Lock.vue')['default']
  const MyDialog: typeof import('./../components/MyDialog.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const Settings: typeof import('./../components/HomeView/Settings.vue')['default']
  const TheWelcome: typeof import('./../components/TheWelcome.vue')['default']
  const WelcomeItem: typeof import('./../components/WelcomeItem.vue')['default']
}